export const columns = [
  {
    id: 'name',
    data: 'name',
    title: 'Name',
    required: true,
    type: 'dropdown',
    width: 150,
    source: [
      'Lee Garcia',
      'Tanya Carr',
      'Winfred Dennis',
      'Wayne Stokes',
      'Tom Owens',
      'Jeremy Mac',
      'Yolanda Kelley',
      'Wm Alvarado',
      'Tiffany Ingram',
      'Steve Forbes',
      'James Gillis',
      'Richard Macaulay',
      'Krakatoa Ventures',
      'Barbara C. Lemieux',
      'Jason B. McNair',
      'Brad S. Astle',
      'Judith C. Nichols',
      'Jesse C. Stewart',
      'Brandy Sparks',
      'Gene Reeves',
      'Boyd Santiago',
      'Clara Moreno',
      'May Barber',
      'Stewart Carpenter',
      'Cheryl Garner',
      'Oscar Jensen',
      'Melinda Todd',
      'Faith Clarke',
      'Jill Lawson',
      'Allan Ortega',
      'Jake Gomez',
      'Hubert Torres',
      'Dale Robertson',
      'Annie Logan',
      'Laverne Cooper',
      'Julian Houston',
      'Kara Cannon',
      'Lisa Kelly',
      'Milton Davidson',
      'Nicholas Parks',
      'Kyle Santos',
      'Kelli Abbott',
      'Kerry Hudson',
      'Bryant Clayton',
      'Clifton Mclaughlin',
      'Duane Higgins',
      'Lucas Ruiz',
      'John Simmons',
      'Sheila Cross',
      'Margaret Bryan',
      'Essie Goodwin',
      'Noel Tran',
      'Julia Franklin',
      'Kirk Gross',
      'Anita Wright',
      'Glen Buchanan',
      'Larry Mccoy',
      'Jerald Graham',
      'Earnest Guerrero',
      'Lindsey Boone',
      'Jaime Freeman',
      'Grady Webb',
      'Aubrey Parsons',
      'Luis Bowman',
      'Bernice Yates',
      'Matthew Wallace',
      'Ollie Christensen',
      'Nelson Weber',
      'Miranda Bell',
      'Dan Gonzales',
      'Camille Carson',
      'Morris Thompson',
      'Roy Gonzalez',
      'Anne Maldonado',
      'Karl Gregory',
      'Levi Walker',
      'Philip Hampton',
      'Guillermo Hicks',
      'Antonio Campbell',
      'Michelle Osborne',
      'Janice Townsend',
      'Lydia Briggs',
      'Candace Pierce',
      'Joy Brown',
      'Eric Payne',
      'Johnny Murphy',
      'Bob Holland',
      'Leroy Day',
      'Sally Nguyen',
      'Lillian Lopez',
      'Harvey Cohen',
      'Gretchen Rodriguez',
      'Leah Clark',
      'Ricky Haynes',
      'Shelley Paul',
      'Jackie Frank',
      'Ron Wolfe',
      'Krakatoa Ventures Fund I',
      'Winifred Dennis',
      'Kevin McKnight',
      'Ross Jones',
      'Jaireh Abdula',
      'Kuni Sugiyama',
      'Simon Davis',
      'Jake Pappas',
      'Jack Greene',
      'Sandy S.Miller',
      'MD Technology Partners, L.P.',
      'Paul Jones',
      'Mary Stuart',
      'Bart Smith',
      'Laplante Ventures II, LP',
      'Almanza Family Trust',
      'Foreman & Forester LP',
      'Irving Brady',
      'Irving Brady',
      'Joao das Neves',
      'Goddard Capital Fund I, LP',
      'Krakatoa Ventures Fund VII, L.P.',
      'Alexander Wagner',
      'Wilson Family Trust',
      'Tagg Jones',
      'Adrienneo Williamson',
      'JR Quarnberg',
      'Janet Sugiyama',
      'Jennie Craw',
      'Jake Pappas',
      'Simon Davis',
      'Rainier Ventures',
      'Lapoint Ventures',
      'Jeremy D. Mac',
      'Jane Porter',
      'Jared Firestone',
      'Krakatoa Ventures',
      'John Smith',
      'Anne C. Caron',
      'Benny Moran',
      'Tyrone Harrison',
      'Tagg Palmer',
      'Krakatoa Ventures Fund I, L.P.',
      'Emilyo Wilson',
      'Emily Wilson',
      'Maria Lucia Fifita',
      'Jason Hammond',
      'Sara Morales',
      'Alan Harris',
      'Money Wagon',
      'Everest Corp',
      'Royal Finance',
      "Fred Admin'strator",
      'Aaron Kim',
      'Ivan Gilson',
      'Michael Edmonson',
      'Jeanette Davis',
      'Fred Charleston',
      'Margaret Hart',
      'Tracey Hill',
      'Mark Watney',
      'Test Service Account',
    ],
    slider: {
      helpText: 'The full name of the stakeholder (person or entity) whom this security shall be granted or issued to.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'email',
    data: 'email',
    title: 'Email',
    required: true,
    type: 'dropdown',
    width: 150,
    source: [
      'lee@example.com',
      'tanyacarr@example.com',
      'winifreddennis@example.com',
      'waynestokes@example.com',
      'tomowens@example.com',
      'jeremy@krakatoavc.com',
      'yolandakelley@example.com',
      'wmalvarado@example.com',
      'tiffanyingram@example.com',
      'steve@example.com',
      'james@krakatoavc.com',
      'richard@example.com',
      'paul@esharesinc.com',
      'barbara@example.com',
      'jason@example.com',
      'brad@example.com',
      'judith@example.com',
      'jesse@example.com',
      'brandysparks@example.com',
      'genereeves@example.com',
      'boydsantiago@example.com',
      'claramoreno@example.com',
      'maybarber@example.com',
      'stewartcarpenter@example.com',
      'cherylgarner@example.com',
      'oscarjensen@example.com',
      'melindatodd@example.com',
      'faithclarke@example.com',
      'jilllawson@example.com',
      'allanortega@example.com',
      'jakegomez@example.com',
      'huberttorres@example.com',
      'dalerobertson@example.com',
      'annielogan@example.com',
      'lavernecooper@example.com',
      'julianhouston@example.com',
      'karacannon@example.com',
      'lisakelly@example.com',
      'miltondavidson@example.com',
      'nicholasparks@example.com',
      'kylesantos@example.com',
      'kelliabbott@example.com',
      'kerryhudson@example.com',
      'bryantclayton@example.com',
      'cliftonmclaughlin@example.com',
      'duanehiggins@example.com',
      'lucasruiz@example.com',
      'johnsimmons@example.com',
      'sheilacross@example.com',
      'margaretbryan@example.com',
      'essiegoodwin@example.com',
      'noeltran@example.com',
      'juliafranklin@example.com',
      'kirkgross@example.com',
      'anitawright@example.com',
      'glenbuchanan@example.com',
      'larrymccoy@example.com',
      'jeraldgraham@example.com',
      'earnestguerrero@example.com',
      'lindseyboone@example.com',
      'jaimefreeman@example.com',
      'gradywebb@example.com',
      'aubreyparsons@example.com',
      'luisbowman@example.com',
      'berniceyates@example.com',
      'matthewwallace@example.com',
      'olliechristensen@example.com',
      'nelsonweber@example.com',
      'mirandabell@example.com',
      'dangonzales@example.com',
      'camillecarson@example.com',
      'morristhompson@example.com',
      'roygonzalez@example.com',
      'annemaldonado@example.com',
      'karlgregory@example.com',
      'leviwalker@example.com',
      'philiphampton@example.com',
      'guillermohicks@example.com',
      'antoniocampbell@example.com',
      'michelleosborne@example.com',
      'janicetownsend@example.com',
      'lydiabriggs@example.com',
      'candacepierce@example.com',
      'joybrown@example.com',
      'ericpayne@example.com',
      'johnnymurphy@example.com',
      'bobholland@example.com',
      'leroyday@example.com',
      'sallynguyen@example.com',
      'lillianlopez@example.com',
      'harveycohen@example.com',
      'gretchenrodriguez@example.com',
      'leahclark@example.com',
      'rickyhaynes@example.com',
      'shelleypaul@example.com',
      'jackiefrank@example.com',
      'ronwolfe@example.com',
      'kerri@krakatoavc.com',
      'winifreddennis@example.com',
      'kevin.mcknight@example.com',
      'ross.jones@example.com',
      'jaireh.abdula@example.com',
      'kuni.sugiyama@example.com',
      'simon.davis@example.com',
      'jake.pappas@example.com',
      'jackgreene@example.com',
      'sandy.miller@example.com',
      'paul@krakatoavc.com',
      'paul@esharesinc.com',
      'mary@esharesinc.com',
      'bartsmith@esharesinc.com',
      'admin@esharesinc.com',
      'aft@example.com',
      'foreman@example.com',
      'irving@esharesinc.com',
      'irving@esharesin.com',
      'joao@carta.com',
      'robert.goddard@esharesinc.com',
      'kerri@krakatoavc.com',
      'alexanderwagner@example.comm',
      'emily@esharesinc.com',
      'tagg+1@esharesinc.com',
      'adriennewilliamson@example.comm',
      'demo-ccmx+jr@carta.com',
      'janet.sugiyama@example.com',
      'jennie.craw@example.com',
      'jake.pappas@krakatoavc.com',
      'simon.davis@krakatoavc.com',
      'rainier@example.com',
      'lapoint@example.com',
      'jeremy@krakatoavc.com',
      'jane.porter@example.com',
      'jared.firestone@example.com',
      'tagg@esharesinc.com',
      'john.smith@example.com',
      'anne@example.com',
      'bennymoran@example.com',
      'tyroneharrison@example.com',
      'tagg@esharesinc.com',
      'paul@krakatoavc.com',
      'emily@esharesinc.comm',
      'emily@esharesinc.com',
      'mlf@esharesinc.com',
      'jason.hammond@carta.com',
      'sara.morales@carta.com',
      'alan.harris@carta.com',
      'money.wagon@carta.com',
      'everest@carta.com',
      'royalfinance@carta.com',
      'admin@esharesinc.com',
      'aaron@example.com',
      'ivan@example.com',
      'michael@example.com',
      'jeanette@example.com',
      'fred@esharesinc.com',
      'margaret@example.com',
      'tracey.hill@carta.com',
      'mark.watney@carta.com',
      'testserviceaccount@example.com',
    ],
    slider: {
      helpText:
        "The email address of the stakeholder, recommended to use their personal email, or their appointed individual who has power-of-attorney. If the security holder is a minor (under the age of 18), then the email address is that of the minor's legal guardian.",
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'stakeholderKind',
    data: 'stakeholderKind',
    title: 'Stakeholder type',
    required: true,
    type: 'dropdown',
    width: 120,
    source: ['Non-individual', 'Individual'],
    slider: {
      helpText:
        'An individual stakeholder is meant to be one person. Non-individual is for any stakeholder that is an entity, for example a trust or fund.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'issueDateRelationship',
    data: 'issueDateRelationship',
    title: 'Relationship',
    required: true,
    type: 'dropdown',
    width: 120,
    source: [
      'Investor',
      'Founder',
      'Advisor',
      'Ex-Advisor',
      'Board member',
      'Consultant',
      'Ex-Consultant',
      'Employee',
      'Ex-Employee',
      'Executive',
      'International Employee',
      'Officer',
      'Other',
    ],
    slider: {
      helpText:
        'Stakeholder relationship is used for stock compensation expense accounting to determine whether the awards expense falls under topic ASC-718 (Employee awards) or ASC-505-50 (Non-employee awards).\n\n"Employees" typically receive a W-2 while "non-employees" typically receive 1099\'s, with the exception of board members.',
    },
    wordWrap: false,
  },
  {
    id: 'shareClass',
    data: 'shareClass',
    title: 'Share class',
    required: true,
    type: 'dropdown',
    width: 120,
    source: [
      '(CS) Common',
      '(PS) Series Seed Preferred',
      '(PA) Series A Preferred',
      '(PB) Series B Preferred',
      '(PC) Series C Preferred',
      '(PD) Series D Preferred',
      '(PSB) Series B II Preferred',
    ],
    slider: {
      helpText:
        'Share class that the certificates originate from. Preferred shares will originate from a newly created preferred share class while founder shares typically originate from a common share class.',
    },
    wordWrap: false,
  },
  {
    id: 'prefixNumber',
    data: 'prefixNumber',
    title: 'Certificate #',
    type: 'text',
    width: 90,
    slider: {
      helpText:
        'Certificate number is an optional field to explicitly set the number. If left blank, the certificate number automatically increments from the last issued certificate number.',
    },
    wordWrap: false,
  },
  {
    id: 'quantity',
    data: 'quantity',
    title: 'Quantity',
    required: true,
    type: 'numeric',
    width: 90,
    numericFormat: {
      pattern: {
        thousandSeparated: true,
      },
    },
    slider: {
      helpText: 'The number of grants or shares the stakeholder may receive for this security.',
    },
    wordWrap: false,
  },
  {
    id: 'lawFirmPrice',
    data: 'lawFirmPrice',
    title: 'Price per share',
    required: true,
    type: 'numeric',
    width: 90,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText:
        'The price per share for the certificate is typically the original issue price on the share class; however, can also represent the discounted price for the conversion of a convertible instrument.',
    },
    wordWrap: false,
  },
  {
    id: 'cashPaid',
    data: 'cashPaid',
    title: 'Cash paid',
    type: 'numeric',
    width: 150,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText: 'The amount paid or capital contribution for all shares on the certificate',
    },
    wordWrap: false,
  },
  {
    id: 'convertibleNote',
    data: 'convertibleNote',
    title: 'Converted from',
    type: 'dropdown',
    width: 180,
    source: ['Multiple convertible notes'],
    slider: {},
    wordWrap: false,
    validation: {},
  },
  {
    id: 'debtCanceled',
    data: 'debtCanceled',
    title: 'Debt canceled',
    type: 'numeric',
    width: 90,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText:
        'The amount of debt canceled for all shares on the certificate. Typically the principal and interest on the convertible instrument at the time of conversion.',
    },
    wordWrap: false,
  },
  {
    id: 'currency',
    data: 'currency',
    title: 'Currency',
    required: true,
    type: 'dropdown',
    width: 90,
    source: [
      'USD',
      'AUD',
      'ARS',
      'BRL',
      'BGN',
      'CAD',
      'CLP',
      'CNY',
      'COP',
      'HRK',
      'CZK',
      'DKK',
      'EUR',
      'HKD',
      'HUF',
      'IDR',
      'INR',
      'ISK',
      'JPY',
      'KES',
      'KRW',
      'MXN',
      'MYR',
      'MUR',
      'NOK',
      'ILS',
      'RON',
      'ANG',
      'NZD',
      'PHP',
      'PLN',
      'GBP',
      'RUB',
      'SGD',
      'ZAR',
      'SEK',
      'CHF',
      'THB',
      'VND',
    ],
    slider: {
      helpText: 'The currency of the security price.',
    },
    wordWrap: false,
  },
  {
    id: 'boardApprovalDate',
    data: 'boardApprovalDate',
    title: 'Board approval date',
    required: true,
    type: 'date',
    width: 120,
    slider: {
      helpText:
        'The date the board signed a Board Consent approving the issuance of shares.\n\nTypically the board approval date is earlier or the same as the grant date and after the vesting start date.',
    },
    wordWrap: false,
  },
  {
    id: 'issueDate',
    data: 'issueDate',
    title: 'Issue date',
    required: true,
    type: 'date',
    width: 120,
    slider: {
      helpText:
        'The date the stakeholder receives the grant from the company. This date must be today or before today.\n\nTypically grant date is the same as or after board approval date and after vesting start date.',
    },
    wordWrap: false,
  },
  {
    id: 'rule144Date',
    data: 'rule144Date',
    title: 'Rule 144 date',
    required: true,
    type: 'date',
    width: 120,
    slider: {
      helpText:
        'Rule 144 is an exemption that allows the sale of restricted and control securities in the public marketplace if certain conditions are met. According to the SEC, these securities are “acquired in unregistered, private sales from the issuing company or from an affiliate of the issuer,” which may include stock benefit plans to employees, preferred issuances from capital contributions and transfer agreements between stakeholders. Consult with your legal team regarding which Rule 144 date should be used on certificates.',
      helpLink: 'https://support.carta.com/s/article/rule-144',
    },
    wordWrap: false,
  },
  {
    id: 'vestingStartDate',
    data: 'vestingStartDate',
    title: 'Vesting start date',
    type: 'date',
    width: 120,
    slider: {
      helpText:
        'Vesting start date or commencement date is the when the options or shares can begin vesting.\n\nFor new hires, it is typically the new hire start date and should be on or before the Board Approval date.',
    },
    wordWrap: false,
  },
  {
    id: 'vestingTemplate',
    data: 'vestingTemplate',
    title: 'Vesting schedule',
    required: true,
    type: 'dropdown',
    width: 180,
    source: [
      '1/48, No Cliff',
      '1/24, No Cliff',
      '1/48, 1Y cliff',
      'Annual EBIDTA Target',
      'test',
      'Boxcar vesting',
      'No vesting',
      '+ New vesting schedule',
    ],
    slider: {
      helpText:
        'Vesting is the process of earning an asset or right to exercise an asset. Vesting generally occurs incrementally over time but may also tie to milestones. Carta supports three common types of vesting schedules: time-based, milestone-based, and a hybrid of time-based and milestone-based.\n\nWith time-based stock vesting, you earn options or shares over time. Most time-based vesting schedules have a vesting cliff. A cliff is when the first portion of your option grant vests. After the cliff, you usually gradually vest the remaining options each month or quarter. Any unvested options get put back into the option pool when you leave (and after the post-termination exercise period has elapsed).\n\nWith milestone vesting, you get your options or shares after completing a specific project or when you and/or the company reach a business goal (e.g. the company hits a certain valuation). This type of vesting isn’t as common as time-based vesting.\n\nHybrid vesting is a combination of time-based and milestone vesting. With hybrid vesting, you have to both work at the company for a certain amount of time and hit one or more milestones to receive your options or shares.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'vestingAccelerationName',
    data: 'vestingAccelerationName',
    title: 'Acceleration terms',
    type: 'dropdown',
    width: 180,
    source: ['No acceleration', '+ New acceleration terms'],
    slider: {
      helpText: 'Description of terms where vesting can be accelerated.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'legendName',
    data: 'legendName',
    title: 'Build legend',
    required: true,
    type: 'dropdown',
    width: 180,
    source: ['Default', 'Custom 1', 'Transfer Restrictions', 'Right of First Refusal (ROFR)', 'Custom Legend'],
    slider: {
      helpText: 'An exercise legend is a statement on a certificate noting restrictions on the transfer of the stock.',
    },
    wordWrap: false,
  },
  {
    id: 'exemption',
    data: 'exemption',
    title: 'Federal exemption',
    required: true,
    type: 'dropdown',
    width: 150,
    source: [
      'Rule 701',
      'Section 4(a)(2)',
      'Section 4(a)(1-1/2)',
      'Section 4(a)(7)',
      'Rule 144',
      'Reg D - 506(b)',
      'Reg D - 506(c)',
      'Reg D - 506',
      'Reg D - 505',
      'Reg D - 504',
      'Reg S',
      'Reg A (Tier 1)',
      'Reg A (Tier 2)',
      'Reg CF',
      'Non-U.S.',
      'Other',
    ],
    slider: {
      helpText:
        'Section 4(a)(2) of the Securities Act exempts from registration "transactions by an issuer not involving any public offering." To qualify for this exemption, which is sometimes referred to as the “private placement” exemption, the purchasers of the securities must.\n\nRule 701\nA rule under the Securities Act that provides a safe harbor from registration under the Securities Act for grants of equity securities by a non-reporting company to its employees and certain other persons under a written compensatory benefit plan or written compensation contract. Securities acquired in Rule 701 transactions are restricted securities, however, under Rule 701(g)(3), they benefit from favorable treatment under Rule 144 after a company goes public.',
      helpLink: 'https://support.carta.com/s/article/choosing-federal-exemptions',
    },
    wordWrap: false,
  },
  {
    id: 'stateOfResidency',
    data: 'stateOfResidency',
    title: 'State of residency',
    type: 'text',
    width: 150,
    slider: {
      helpText: 'The state of residency of the stakeholder who is receiving the equity.',
    },
    wordWrap: false,
    validation: {
      errorMessage: 'Replace text with 2 letter US state code or 3 letter country code',
    },
  },
  {
    id: 'stateExemption',
    data: 'stateExemption',
    title: 'State exemption',
    type: 'text',
    width: 150,
    slider: {
      helpText: 'Refer to your counsel for guidance on state exemption.',
    },
    wordWrap: false,
  },
  {
    id: 'valueOfIpTransferred',
    data: 'valueOfIpTransferred',
    title: 'Value of IP transferred',
    type: 'numeric',
    width: 90,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText: 'The amount of value that IP contributed for shares on the certificate.',
    },
    wordWrap: false,
  },
  {
    id: 'otherConsideration',
    data: 'otherConsideration',
    title: 'Other consideration',
    type: 'numeric',
    width: 90,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText: 'The amount of value contributed for shares on the certificate.',
    },
    wordWrap: false,
  },
  {
    id: 'employeeId',
    data: 'employeeId',
    title: 'Employee ID',
    type: 'text',
    width: 150,
    slider: {
      helpText: 'Employee ID as defined by your HR management system.',
    },
    wordWrap: false,
  },
  {
    id: 'jobTitle',
    data: 'jobTitle',
    title: 'Job title',
    type: 'dropdown',
    width: 150,
    source: ['Director of marketing', 'Senior engineer'],
    slider: {
      helpText: 'The job title of the stakeholder who is receiving the equity.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'salary',
    data: 'salary',
    title: 'Annual salary',
    type: 'numeric',
    width: 150,
    numericFormat: {
      pattern: {
        output: 'currency',
        thousandSeparated: true,
        spaceSeparated: true,
      },
    },
    slider: {
      helpText: 'The annual salary of the stakeholder who is receiving the equity.',
    },
    wordWrap: false,
  },
  {
    id: 'rule144DifferenceReason',
    data: 'rule144DifferenceReason',
    title: 'Rule 144 difference reason',
    type: 'dropdown',
    width: 150,
    source: [
      'Company has determined Rule 144 date by other exemption',
      'Securities are no longer deemed restricted as described in Rule 144(a)(3)',
      'Stock dividends, splits, recapitalizations, conversions and exchanges as described in Rule 144(d)(3)(i)-(ii)',
      'Restricted securities gifted between affiliates',
      'Restricted securities purchased from another non-affiliate',
    ],
    slider: {
      helpText: 'Refer to your counsel for guidance on why issue date and rule 144 dates do not match.',
    },
    wordWrap: false,
  },
  {
    id: 'documentSet',
    data: 'documentSet',
    title: 'Documents',
    required: false,
    type: 'dropdown',
    width: 180,
    source: ['+ New documents'],
    slider: {
      helpText:
        'Documents are automatically pulled from predefined Document Sets in Templates. However, if you wish to create a custom set of documents, simply select "Custom Documents" in the dropdown.',
    },
    wordWrap: false,
    validation: {},
  },
  {
    id: 'notes',
    data: 'notes',
    title: 'Notes',
    type: 'text',
    width: 150,
    slider: {
      helpText: 'Additional notes to record on the security.',
    },
    wordWrap: false,
  },
  {
    id: 'customVesting',
    data: 'customVesting',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'attachments',
    data: 'attachments',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'attachmentsUuid',
    data: 'attachmentsUuid',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'attachmentObjs',
    data: 'attachmentObjs',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'legendPks',
    data: 'legendPks',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'convertibleNotes',
    data: 'convertibleNotes',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'vestingAcceleration',
    data: 'vestingAcceleration',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
  {
    id: 'customAcceleration',
    data: 'customAcceleration',
    title: '',
    type: 'text',
    width: 180,
    wordWrap: false,
    validation: {},
  },
];

export const defaultColumnSettings = {
  typeahead: {
    type: 'autocomplete',
    strict: true,
    width: 140,
    validator: 'AutocompleteValidator',
    validation: {
      errorMessage: 'This field should be one of the provided options',
    },
  },
  datepicker: {
    type: 'date',
    width: 120,
    dateFormat: 'MM/DD/YYYY',
    strict: true,
    correctFormat: true,
    datePickerConfig: {
      showWeekNumber: true,
    },
    validator: 'DateValidator',
    validation: {
      errorMessage: 'This field should follow the format MM/DD/YYYY',
    },
  },
  dropdown: {
    type: 'dropdown',
    strict: true,
    width: 140,
    validator: 'DropdownValidator',
    validation: {
      errorMessage: 'This field should be one of the provided options',
    },
  },
  numeric: {
    type: 'numeric',
    className: 'htRight',
    numericFormat: {
      pattern: {
        optionalMantissa: true,
        thousandSeparated: true,
        mantissa: 2,
      },
    },
    width: 140,
    validator: 'NumericValidator',
    validation: {
      errorMessage: 'This field should be a number',
    },
  },
  text: {
    type: 'text',
    width: 160,
    validation: {
      errorMessage: 'Invalid value',
    },
  },
  checkbox: {
    type: 'checkbox',
    width: 120,
    validation: {
      errorMessage: 'Invalid value',
    },
  },
  currency: {
    type: 'numeric',
    numericFormat: {
      pattern: '$ 0,0.00',
    },
    width: 150,
    validator: 'NumericValidator',
    validation: {
      errorMessage: 'This field should be a number',
    },
  },
  percentage: {
    type: 'numeric',
    numericFormat: {
      pattern: {
        output: 'percent',
        optionalMantissa: true,
        mantissa: 2,
        thousandSeparated: true,
      },
    },
    width: 140,
    validator: 'NumericValidator',
    validation: {
      errorMessage: 'This field should be a number',
    },
  },
};
